# Header

menu:
  首页: /
#  杂记: /tags/essay/
  归档: /archives/

# SubNav
subnav:
  github: "https://github.com/haowanxing"
  weibo: "http://weibo.com/u/2214092525"
  #rss: "#"
  #zhihu: "#"
  #qq: "#"
  #weixin: "#"
  #jianshu: "#"
  #douban: "#"
  #segmentfault: "#"
  #bilibili: "#"
  #acfun: "#"
  mail: "mailto:smoothest@yeah.net"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root: 

# Content

# 文章太长，截断按钮文字
excerpt_link: '继续阅读'
# 文章卡片右下角常驻链接，不需要请设置为false
show_all_link: '展开全文'
# 数学公式
mathjax: false
# 是否在新窗口打开链接
open_in_new: false

# 打赏
# 请在需要打赏的文章的md文件头部，设置属性reward: true

# 打赏基础设定：0-关闭打赏； 1-文章对应的md文件里有reward:true属性，才有打赏； 2-所有文章均有打赏
reward_type: 2
# 打赏wording
reward_wording: '谢谢你请我吃糖果'
# 支付宝二维码图片地址，跟你设置头像的方式一样。比如：/assets/img/alipay.jpg
alipay: https://www.imsry.cn/uploads/qiniu/20171110151028534092711.png
#https://i.loli.net/2017/08/14/599170028a37a.jpg
#https://ooo.0o0.ooo/2017/03/12/58c51819ae815.png #/img/alipay.png #https://www.imsry.cn/uploads/qiniu/2017011914847919192601.jpg?imageView2/0/format/jpg
# 微信二维码图片地址
weixin: https://www.imsry.cn/uploads/qiniu/20171110151028574147502.png
#https://i.loli.net/2017/08/14/59917034387ba.jpg
#/img/wxpay.png #https://www.imsry.cn/uploads/qiniu/20170119148479221163508.jpg?imageView2/0/format/jpg

# Miscellaneous
baidu_analytics: 'db81841d8218c843f1e0f9b9abdef3a8'
google_analytics: ''
favicon: /favicon.png

#你的头像url
#avatar: https://ooo.0o0.ooo/2017/05/16/591af188ce905.png
#avatar: https://i.loli.net/2017/08/14/599168f1ba854.jpg
#avatar: https://www.imsry.cn/uploads/qiniu/20171110151028587697208.jpg
avatar: https://www.imsry.cn/uploads/qiniu/20181010153914990649885.png

#是否开启分享
share_jia: true

#评论：1、多说；2、网易云跟帖；3、畅言；4、Disqus 不需要使用某项，直接设置值为false，或注释掉
#具体请参考wiki：https://github.com/litten/hexo-theme-yilia/wiki/

#1、多说
duoshuo: false

#2、网易云跟帖
wangyiyun: false

#3、畅言
changyan_appid: false
changyan_conf: false

#4、Disqus 在hexo根目录的config里也有disqus_shortname字段，优先使用yilia的
disqus: false #'imsry'

#5、gitment
gitment: true

# 样式定制 - 一般不需要修改，除非有很强的定制欲望…
style:
  # 头像上面的背景颜色
  header: '#4d4d4d'
  # 右滑板块背景
  slider: 'linear-gradient(200deg,#a0cfe4,#e8c37e)'

# slider的设置
slider:
  # 是否默认展开tags板块
  showTags: false

# 智能菜单
# 如不需要，将该对应项置为false
# 比如
#smart_menu:
#  friends: false
smart_menu:
  innerArchive: '目录'
  friends: '友链'
  aboutme: '关于'

friends:
  EyeEm: https://www.eyeem.com/u/anthony_box
  \0x4f5da2: http://www.0x4f5da2.cn/
  HEL: http://www.h-five.com/
  Jerry Qu: https://imququ.com/

aboutme: 　　博主会在适当时间更新笔记和尝试原创。<br><br>　　如果你认为我的文章对你有帮助，欢迎将本站推荐给你的小伙伴，也可以尝试一下每篇文章结尾的“赞赏”功能。
